#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: reflash the Redion Wind Sim, with a rollback taken first.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

AVR_HOME="C:/Program Files (x86)/SimHub/_Addons/Arduino/ArduinoIDE/arduino-1.6.13/hardware/tools/avr"
AVRDUDE="$AVR_HOME/bin/avrdude.exe"
AVRCONF="$AVR_HOME/etc/avrdude.conf"
PORT="${WIND_PORT:-COM5}"
BASELINE="reference/simhub-baseline"
STAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP="$BASELINE/redion-flash-backup-$STAMP.hex"
VERIFY="$BASELINE/.verify-$STAMP.hex"

# read_flash FILE: pull the board's flash to FILE. Tries the modern bootloader
# rate first, then the older one - a clone Uno may be either, and "not in
# sync" at 115200 usually means 57600.
read_flash() {
  "$AVRDUDE" -C "$AVRCONF" -c arduino -p m328p -P "$PORT" -b 115200 \
      -U "flash:r:$1:i" >/dev/null 2>&1 && return 0
  say "115200 did not sync; trying 57600 (older bootloader)."
  "$AVRDUDE" -C "$AVRCONF" -c arduino -p m328p -P "$PORT" -b 57600 \
      -U "flash:r:$1:i" >/dev/null 2>&1
}

newest_backup() { ls -1t "$BASELINE"/redion-flash-backup-*.hex 2>/dev/null | head -1; }

# ── restore mode: --restore puts the saved image back and exits ────────────
if [[ "${1:-}" == "--restore" ]]; then
  # Not `banner`: that one counts stages and talks about a browser, and this
  # path is a single command against a board.
  printf '
  %sWind sim: restore the original firmware%s

' "$BOLD" "$RESET"
  have="$(newest_backup || true)"
  if [[ -z "$have" ]]; then
    say "No backup in $BASELINE. There is nothing to restore to."
    say "Run this script without --restore first; stage 2 takes one."
    exit 1
  fi
  say "Restoring: $have"
  say "Close Pit Crew and SimHub first - two programmes must not hold $PORT."
  confirm "Write that image back to the board on $PORT?" || exit 0
  if "$AVRDUDE" -C "$AVRCONF" -c arduino -p m328p -P "$PORT" -b 115200 -D \
        -U "flash:w:$have:i"; then
    say "Restored. The board is back to how it was before the reflash."
  else
    say "Write failed. Try -b 57600 by hand, or reflash from SimHub"
    say "(shield count 1, PWM fans 0, frequency 1200)."
    exit 1
  fi
  exit 0
fi

banner "Wind sim reflash: 1200 Hz -> 1900 Hz"
say "There is no browser in this one. It drives avrdude for the backup, then"
say "tells you what to change in SimHub's setup tool, then leaves you a"
say "one-command way back."
say ""

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Free the port"
say "Two programmes must not both hold $PORT, and avrdude needs it alone."
step "Quit Pit Crew if it is running."
step "Quit SimHub, or untick its output for this device."
pause "Both closed?"
if [[ ! -x "$AVRDUDE" ]]; then
  say "avrdude is not at the expected path:"
  say "  $AVRDUDE"
  say "Install SimHub's Arduino add-on, or edit AVR_HOME at the top of this"
  say "script. Nothing has been touched."
  exit 1
fi
say "avrdude found."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Back up the flash - this is the rollback"
say "Nothing else in this procedure is reversible without this file, and"
say "there is no backup on disk today: the command was written down on"
say "3 Sep and never run."
say ""
say "Reading the board resets it. Measured on this rig 15 Aug: the fans do"
say "not spin during a reset. Have the PSU on and the fans clear anyway."
confirm "Read the flash from $PORT now?" || { say "Stopped. Nothing changed."; exit 0; }
mkdir -p "$BASELINE"
if ! read_flash "$BACKUP"; then
  say "Read failed. The board did not answer on $PORT at either rate."
  say "Check the cable and that nothing else holds the port. Nothing changed."
  exit 1
fi
size=$(wc -c < "$BACKUP" | tr -d ' ')
if [[ "$size" -lt 1024 ]]; then
  say "The file is only ${size} bytes, which is not a firmware image."
  say "A good read is a few tens of kB. Nothing has been written to the board."
  rm -f "$BACKUP"
  exit 1
fi
say "Wrote $BACKUP (${size} bytes)."
say ""
say "Now reading a second time to prove the image is faithful. A backup that"
say "has never been checked is not a rollback, it is a file."
if read_flash "$VERIFY" && cmp -s "$BACKUP" "$VERIFY"; then
  rm -f "$VERIFY"
  say "Two reads are byte-identical. This is a real image."
else
  rm -f "$VERIFY"
  say "The two reads DIFFER, or the second failed. Do not trust this backup."
  say "Re-run this stage before going any further."
  exit 1
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Change the shield frequency in SimHub"
say "Your fans are TWO-WIRE, so the 25 kHz PWM-fan conversion in sections 3-4"
say "of the reference doc does not apply - there is no control wire to drive."
say "The change that does apply is one number."
say ""
step "Start SimHub. Left menu: Arduino. Open 'Arduino setup tool'."
step "Choose Single Arduino. Board: Uno. Port: $PORT."
step "Leave every feature exactly as it is. Change ONLY:"
say "      SHAKEIT Adafruit Motorshield V2"
say "      -> motor shield PWM frequency:  1200  ->  1900"
step "Keep the device name 'Redion Wind Sim'. A new unique id is fine;"
say "      Pit Crew does not read it."
step "Upload to Arduino. Watch the compile, then the upload."
step "When it finishes, SimHub's Arduino page should still show 4 motors."
say "      If it shows 0, the shield count was changed by mistake - set it"
say "      back to 1 and upload again."
pause "Upload finished?"
step "Quit SimHub, or untick its output for this device."
pause "SimHub closed?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Test it on the bench, before the car"
say "The prediction under test: the dropouts are a STARTING fault - they"
say "appear as duty rises and not as it falls. If they show in both"
say "directions it is a running fault and this reflash is the wrong fix."
say ""
step "Run the sweep and mark whatever you hear:"
say "      python tools/wind_sweep.py sweep --channels 0,1 --step 8"
step "Then a real stint, and watch for the corner-exit drop specifically."
pause "Tested?"
ask WIND_REFLASH_VERDICT "Better, same, or worse?"
say "Recorded: $WIND_REFLASH_VERDICT"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "If it did not work"
say "The board can go back to exactly what it was, in one command:"
say ""
say "    bash scripts/wind-reflash.sh --restore"
say ""
say "That writes $(basename "$BACKUP") back over the board. It needs"
say "nothing from SimHub and does not depend on this script's other stages."
say ""
say "If the reflash did not help, the next move is the hardware one: a 12 V"
say "supply rated 5 A or more, same barrel. The present one is 12 V 3 A into"
say "a shield whose own limit is 3 A total, driving two blowers - and the"
say "measured swing out of a corner is duty 117 -> 229 of 255, both fans"
say "accelerating together."
say ""
say "Write the verdict into docs/WIND-SKETCH-REFLASH_2026-09-03.md so the"
say "next person does not re-run an experiment that has already been done."

finish
